/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasigudang;

/**
 *
 * @author Asus
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class MenuUtama extends javax.swing.JFrame {

public Connection kon;
private Statement stmt;
private ResultSet rsset;
private PreparedStatement ps;
private DefaultTableModel dtm;
public Login Login;

    /**
     * Creates new form Login
     */
    public MenuUtama() {
        initComponents();
        
        setTitle("Stock Bahan Baku");
        setLocationRelativeTo(null);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            kon = DriverManager.getConnection("jdbc:mysql://localhost:3306/gudang1","root","");
            stmt = kon.createStatement();
        } catch (Exception E) {
        }
        tampilData();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jMenuItem3 = new javax.swing.JMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jPopupMenu7 = new javax.swing.JPopupMenu();
        list1 = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBox1 = new javax.swing.JComboBox();
        tglmasuk = new javax.swing.JPanel();
        KdBarang = new javax.swing.JTextField();
        jenis = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenisbahan = new javax.swing.JTextField();
        ukuran = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kodebarang = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbTampil = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        namabarang = new javax.swing.JLabel();
        ukrn = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        stock1 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        keluar = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem2.setText("jMenuItem2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem3.setText("jMenuItem3");

        popupMenu1.setLabel("popupMenu1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tglmasuk.setBackground(new java.awt.Color(255, 255, 255));

        KdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KdBarangActionPerformed(evt);
            }
        });

        jenis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenis.setText("Jenis Bahan");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasigudang/logo.png"))); // NOI18N

        jenisbahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisbahanActionPerformed(evt);
            }
        });

        ukuran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ukuran.setText("Ukuran");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Input Barang ");

        kodebarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kodebarang.setText("Kode Barang");

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        TbTampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jenis Bahan", "Ukuran", "Stock"
            }
        ));
        TbTampil.getTableHeader().setReorderingAllowed(false);
        TbTampil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbTampilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbTampil);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Ayu Sri Handayani (4513210009) - FTUP 2015");

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jLayeredPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        namabarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namabarang.setText("Nama Barang");

        stock1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stock1.setText("Stock");

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasigudang/hapus.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasigudang/ubah.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        lihat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasigudang/refresh.png"))); // NOI18N
        lihat.setText("Refresh");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tglmasukLayout = new javax.swing.GroupLayout(tglmasuk);
        tglmasuk.setLayout(tglmasukLayout);
        tglmasukLayout.setHorizontalGroup(
            tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tglmasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namabarang)
                        .addComponent(ukuran)
                        .addComponent(jenis)
                        .addComponent(stock1)
                        .addComponent(kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tglmasukLayout.createSequentialGroup()
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(ukrn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisbahan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamabarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KdBarang, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tglmasukLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tglmasukLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpan))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jLayeredPane2)
        );
        tglmasukLayout.setVerticalGroup(
            tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tglmasukLayout.createSequentialGroup()
                .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tglmasukLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tglmasukLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodebarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namabarang)
                            .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis)
                            .addComponent(jenisbahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ukuran)
                            .addComponent(ukrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stock1))
                        .addGap(4, 4, 4))
                    .addGroup(tglmasukLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(tglmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tglmasukLayout.createSequentialGroup()
                                .addComponent(hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edit))
                            .addGroup(tglmasukLayout.createSequentialGroup()
                                .addComponent(simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(batal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lihat)
                        .addGap(18, 18, 18)))
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar4.add(jMenu7);

        jMenu1.setText("Menu");

        keluar.setText("Logout");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuBar4.add(jMenu1);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
         System.exit(0); 
    }//GEN-LAST:event_batalActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            String value1 = KdBarang.getText();
            String value2 = txtnamabarang.getText();
            String value3 = jenisbahan.getText();
            String value4 = ukrn.getText();
            String value5 = stock.getText();
            String sql = "Update bahan_baku set kd_bahan ='"+value1+"',nama = '"+value2+"',jenis_bahan='"+value3+"',ukuran='"+value4+"'"
                    + ",stock='"+value5+"'where kd_bahan = '"+value1+"'";
            ps = kon.prepareStatement(sql);
            ps.execute();
            bersih();
            JOptionPane.showMessageDialog(null, "Edit Data Sukses");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL EDIT"+e);
        }
        
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin menghapus data ini?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            try {
                String sql = "delete from bahan_baku where kd_bahan = '"+KdBarang.getText()+"'";
                Statement stmt = kon.createStatement();
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Menghapus data berhasil");
                bersih();
                } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Menghapus data gagal");
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void KdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KdBarangActionPerformed
       
    }//GEN-LAST:event_KdBarangActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        try{
            Login = new Login();
            Login.setVisible(true);
            this.dispose();
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_keluarActionPerformed
    
    private void tampilData(){
    try{
            Object [] rows = {"Kode Barang", "Nama Barang", "Jenis Barang", "Ukuran", "Stock"};
            dtm = new DefaultTableModel(null, rows);
            TbTampil.setModel(dtm);
            TbTampil.setBorder(null);
            jScrollPane2.setViewportView(TbTampil);
            String kodebarang="",namabarang="",jenis="",ukuran="",stock1="";
            try{
                String sql = "select * from bahan_baku";
                stmt = kon.createStatement();
                ResultSet rsset = stmt.executeQuery(sql);
                    while(rsset.next()){
                        kodebarang = rsset.getString("kd_bahan");
                        namabarang = rsset.getString("nama");
                        jenis = rsset.getString("jenis_bahan");
                        ukuran = rsset.getString("ukuran");
                        stock1 = rsset.getString("stock");
                        
                        String [] tampil = {kodebarang,namabarang,jenis,ukuran,stock1};
                        dtm.addRow(tampil);
                        
                        bersih();
                    }
            }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "QUERY SALAH");
                    
            }
        }catch (Exception e){
          e.printStackTrace();
      }
    }
    
    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
    tampilData();    
    }//GEN-LAST:event_lihatActionPerformed

    private void TbTampilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbTampilMouseClicked
         int i = TbTampil.getSelectedRow();
         if(i>=0){
             KdBarang.setText(dtm.getValueAt(i,0).toString());
             txtnamabarang.setText(dtm.getValueAt(i,1).toString());
             jenisbahan.setText(dtm.getValueAt(i,2).toString());
             ukrn.setText(dtm.getValueAt(i,3).toString());
             stock.setText(dtm.getValueAt(i,4).toString());
         }
        //KdBarang.setText(TbTampil.getValueAt(row, 0).toString());
    }//GEN-LAST:event_TbTampilMouseClicked

    private void jenisbahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisbahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisbahanActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
     
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed

        try{
            String sql = "insert into bahan_baku (kd_bahan, nama, jenis_bahan, ukuran, stock) values ('"+KdBarang.getText()+"','"+txtnamabarang.getText()+"','"+jenisbahan.getText()+"','"+ukrn.getText()+"','"+stock.getText()+"')";
            stmt = kon.createStatement();
            int jumlah = stmt.executeUpdate(sql);
            if (jumlah > 0) {
                JOptionPane.showMessageDialog(null, "DATA SUKSES TERSIMPAN");
            }
            bersih();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL TERSIMPAN" +e);
        }
    }//GEN-LAST:event_simpanActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       /* Create and display the form */
    }
    
     public void bersih (){
        KdBarang.setText("");
        txtnamabarang.setText("");
        jenisbahan.setText("");
        ukrn.setText("");
        stock.setText("");
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KdBarang;
    private javax.swing.JTable TbTampil;
    private javax.swing.JButton batal;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JPopupMenu jPopupMenu7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jenis;
    private javax.swing.JTextField jenisbahan;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JLabel kodebarang;
    private javax.swing.JButton lihat;
    private java.awt.List list1;
    private javax.swing.JLabel namabarang;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel stock1;
    private javax.swing.JPanel tglmasuk;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField ukrn;
    private javax.swing.JLabel ukuran;
    // End of variables declaration//GEN-END:variables


}
